airflow:
  ingress:
    enabled: true
    web:
      host: gies-dsrs.ncsa.illinois.edu
      path: /plumes-airflow

    annotations:
      kubernetes.io/ingress.class: "traefik"

  airflow:
    executor: CeleryExecutor
    config:
      AIRFLOW__WEBSERVER__BASE_URL: 'http://gies-dsrs.ncsa.illinois.edu/plumes-airflow'
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/ncsa/plumes-etl.git
      branch: play
      repoSubPath: dags

  postgresql:
    persistence:
      enabled: false