airflow:
  ingress:
    enabled: true
    web:
      host: gies-dsrs.ncsa.illinois.edu
      path: /smokes-airflow

    annotations:
      kubernetes.io/ingress.class: "traefik"
  executor: KubernetesExecutor
  images:
    airflow:
      pullPolicy: Always
      repository: bengal1/plumes-airflow
      tag: develop

  airflow:
    config:
      AIRFLOW__WEBSERVER__BASE_URL: 'http://gies-dsrs.ncsa.illinois.edu/smokes-airflow'