airflow:
  ingress:
    enabled: true
    web:
      host: gies-dsrs.ncsa.illinois.edu
      path: /smokes-airflow

    annotations:
      kubernetes.io/ingress.class: "traefik"
  flower:
    enabled: false
  redis:
    enabled: false
  workers:
    enabled: false

  airflow:
    executor: KubernetesExecutor
    image:
      pullPolicy: Always
#      repository: bengal1/plumes-airflow
#      tag: develop
    config:
      AIRFLOW__WEBSERVER__BASE_URL: 'http://gies-dsrs.ncsa.illinois.edu/smokes-airflow'